### ISSUE TITLE
Generating Top-N Recommendations for the Recommendation System

### ISSUE THREAD

**Issue by PurushothamanSrikanth** [miguelgfierro/sciblog_support#112]
How to Generating Top-N Recommendations for the [Recommendation System](https://github.com/miguelgfierro/sciblog_support/tree/master/Intro_to_Recommendation_Systems)?

**Comment by miguelgfierro** [comment]
The right way of doing it is by changing the loss function to a ranking loss (like pair-wise loss). 

An easier path, but not totally correct but that many people do, is to get the results the predictions, sort them and get the top-N. It is not correct because the loss is not intended for the task of ranking. But again, it is a technique that many people use because it is easier.

**Comment by PurushothamanSrikanth** [comment]
> The right way of doing it is by changing the loss function to a ranking loss (like pair-wise loss).
> 
> An easier path, but not totally correct but that many people do, is to get the results the predictions, sort them and get the top-N. It is not correct because the loss is not intended for the task of ranking. But again, it is a technique that many people use because it is easier.

@miguelgfierro Can we have this Top-N recommendation as a new feature to the existing one? #112
We can generate Top-N recommendations from the rating prediction matrix.

This is a feature request 😇
