### ISSUE TITLE
Error in Intro_to_Cloud_ML_with_Flask_and_CNTK.ipynb TypeError: Use async with instead

### ISSUE THREAD

**Issue by shirishr** [miguelgfierro/sciblog_support#80]
current version of aiohttp is 3.3.0
I suspect that because of this, the notebook encounters errors.
The moment with **aiohttp.ClientSession() as session:** is executed, it results in error **TypeError: Use async with instead**

**Comment by miguelgfierro** [comment]
The version I used for this notebook was aiohttp==2.0.3, could you try with that?

**Comment by shirishr** [comment]
@miguelgfierro,

Uninstalled aiohttp and reinstalled aiohttp==2.0.3

but got a new error

RuntimeError: This event loop is already running

Full trace:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>()

~/anaconda3/envs/mxnet/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    453         future.add_done_callback(_run_until_complete_cb)
    454         try:
--> 455             self.run_forever()
    456         except:
    457             if new_task and future.done() and not future.cancelled():

~/anaconda3/envs/mxnet/lib/python3.6/asyncio/base_events.py in run_forever(self)
    407         self._check_closed()
    408         if self.is_running():
--> 409             raise RuntimeError('This event loop is already running')
    410         if events._get_running_loop() is not None:
    411             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by miguelgfierro** [comment]
hey @shirishr I added a [conda file](https://github.com/miguelgfierro/sciblog_support/blob/master/Intro_to_Machine_Learning_API/conda.yaml) with the library version that I used one year ago when I did this example. I hope that fixes your error and unblocks you.

I tried to run the notebook again but I found some breaking changes from CNTK and others, that unfortunatelly, I don't have time to fix now.

I would recommend to use this tutorial as a base point for what you want to build, and not take the code as it is, since it is breaking right now.

Good luck!
